### ISSUE TITLE
Please assign a license to the code repository

### ISSUE THREAD

**Issue by virmitio** [damienbod/SelfHostWebApiWithOwinAndUnityUsingNuget#1]
I'm looking to use this package in a project but have been informed by my legal team that due to a lack of explicit license in the project I cannot.

I'm sure this seems an odd request to make a half-dozen years after the latest code commit, but would you be willing to add a LICENSE file to the repo to provide something to point legal teams at to reassure them we'll not be mercilessly sued for using an openly and publicly published package?

**Comment by damienbod** [comment]
Added an MIT license, hope this is good for you

**Comment by virmitio** [comment]
Perfect.  Much appreciated.
